Lewis
akhmaddias/COMP4034-ARS pull request #8
Opened 2020-11-04 18:24 UTC by lew101

WIP:
Dramatically over thought this so I'm going to rework it

2020-11-05 12:02 UTC, BenH14 requested changes
I see what you mean about over-complicating it! Start with the easy stuff (eg obstacle avoidance) and work up to the random walk and wall following. Remember that you're meant to be able to finish this entire task in a couple of hours!

Also, my comments are super nit-picky (One of them is particularly ridiculous, but it is something mentioned in `pep8`).

2020-11-05 12:02 UTC, bhenaghan commented on minitask2/Lewis/walk.py
> +OFFSET_ERROR_LINEAR = 0.01  # Allowable offset from target is 0.01 meters
Nice, I really like that these are all constants

2020-11-05 12:02 UTC, bhenaghan commented on minitask2/Lewis/walk.py
> +        rospy.init_node('Walk', anonymous = True)
Shouldn't have spaces around named parameters.

2020-11-05 12:02 UTC, bhenaghan commented on minitask2/Lewis/walk.py
> +        self.turn_right.angular.z = (-TURN_SPEED)
pretty sure the brackets are redundant here

2020-11-05 12:02 UTC, bhenaghan commented on minitask2/Lewis/walk.py
> +
normally only one newline between methods within a class

2020-11-05 12:02 UTC, bhenaghan commented on minitask2/Lewis/walk.py
> +
There needs to be a `pass` here otherwise your code won't run

2020-11-05 12:02 UTC, bhenaghan commented on minitask2/Lewis/walk.py
> +
Again, need a `pass`

2020-11-05 12:02 UTC, bhenaghan commented on minitask2/Lewis/walk.py
> +    def is_obstacle(self): # MOVE TO ANOTHER NODE
Okay this one is **super** anal but you need two spaces before the `#` then one after. You only have one before.

2020-11-05 12:02 UTC, bhenaghan commented on minitask2/Lewis/walk.py
> +
`pass`

2020-11-05 12:02 UTC, bhenaghan commented on minitask2/Lewis/walk.py
> +        self.drive()
I think calling `drive` would be better in a laserscan callback, rather than odometry (as you need to make urgent decisions based off of the scan data, but odometry data isn't really very relevant most of the time)

2020-11-05 12:02 UTC, bhenaghan commented on minitask2/Lewis/walk.py
> +                    print("[LOG]    Current angle: " + str(self.curr_pose["theta"]))
doing this with `"abc {}".format(def)` or `"abc {0}" % (def)` is more pythonic/readable than doing a normal string concat imo

2020-11-05 12:02 UTC, bhenaghan commented on minitask2/Lewis/walk.py
> +                distance_remaining = self.get_distance_remaining(self.curr_pose["x"], self.curr_pose["y"], self.target["x"], self.target["y"])
put these params on separate lines to make this line a lot shorter.

2020-11-05 12:02 UTC, bhenaghan commented on minitask2/Lewis/walk.py
> +                    self.target = self.get_new_target
You need brackets after this to call the method, you've just set `self.target` to be a reference to the method `get_new_target` - you never actually call the method.

2020-11-05 12:02 UTC, bhenaghan commented on minitask2/Lewis/walk.py
> +        # set target position using polar coordinate maths
This is all very complicated! pick a theta, turn to it and then drive forwards for 3m!

2020-11-05 12:02 UTC, bhenaghan commented on minitask2/Lewis/walk.py
> +
What if `y = 100`, `x=0`, shouldn't the angle be about 90 degrees. Might be wrong here - haven't really thought it through, but my intuition is that there are cases where either x or y can be 0 and the angle should not be 0.

2020-11-05 12:02 UTC, bhenaghan commented on minitask2/Lewis/walk.py
> +                return sqrt((current_x - target_x) ** 2 + (target_y - current_y) ** 2)
You could remove all of the if statements by just using `abs`!

2020-11-05 12:02 UTC, bhenaghan commented on minitask2/Lewis/walk.py
> +            return sqrt((current_x - target_x) ** 2)
Again, use `abs`! You're also squaring something then immediately `sqrt`ing it, you could replace this entire method with `return abs(current_x - target_x)`!

2020-11-05 12:02 UTC, BenH14 commented on minitask2/Lewis/walk.py
> +        pass
normally a good idea to have a newline at the end of the file

2020-11-05 22:57 UTC, lew101 commented on minitask2/Lewis/walk.py
> +
Honestly, I also hadn't thought about this. I'd have to plot arctan and have a look at some point. For now though, this shouldn't be required anymore so I'm going to leave it. A good spot though!

2020-11-06 05:07 UTC, lew101 reviewed
All changed and now nearly working in a fun and interesting way

2020-11-06 05:41 UTC, psymaco commented on minitask2/Lewis/obstacle_avoidance.py
> +        self.turn_left.linear.x = 0
perhaps you should define the zero integers at the beginning?

2020-11-06 13:07 UTC, BenH14 reviewed
This code is a great improvement, and I would say I'm happy with it overall. I do however have a few qualms about the broad design.

I think your intentions are good with splitting the code up into multiple nodes, this is something that is often done with real robotics projects when the behaviours are decently complex. I do think that if you're going to do it this way you really need a 4th node to handle state and when each of the nodes should be giving velocity commands. The ideal way for this to work would be that  each behaviour node publishes a Twist commands to a topic that the controller (4th node) subscribes to, it could then make decisions about which velocity command to publish to `/vel_cmd`. This should make each node much less stateful - something that I would say is the main problem with your current code. 

With ROS being a microservice architecture you can't really rely on your nodes being executed fairly or in any meaningful order,  so the current system of blocking could lead to certain nodes never running (another node always gets there first and locks before it has a chance to block and run). In a bigger robotics project you'll often have something like a controller which makes decisions about which behaviour to run (essentially running a state machine), which will then make requests to behaviour nodes for their required paths. The paths will then be handed to a path following node, which figures out the right velocity commands to send. 

The difference between this kind of architecture and what you've implemented is that there's a clear hierarchy of nodes. In your implementation each node seems to scramble to lock without any authority handling when this should be allowed.

2020-11-06 13:07 UTC, bhenaghan commented on minitask2/Lewis/obstacle_avoidance.py
> +        for i in range(300, 359):
you could do this in one for loop by doing `range(-60,60)` when you index with a negative value in python it counts from the end of the list.

2020-11-06 13:07 UTC, bhenaghan commented on minitask2/Lewis/obstacle_avoidance.py
> +                if self.blocking == False:
You can simplify this to just be `if not self.blocking:` like line `76`

2020-11-06 13:07 UTC, bhenaghan commented on minitask2/Lewis/obstacle_avoidance.py
> +                self.direction = 2
I think this `2` really needs to be a constant to make this clear.

2020-11-06 13:07 UTC, bhenaghan commented on minitask2/Lewis/walk.py
> +        self.curr_pose = {}
All the initialisations can be done in the dict definition: `self.curr_pose = {"theta": 0.0, "x": 0.0, "y": 0.0}`

2020-11-06 13:07 UTC, bhenaghan commented on minitask2/Lewis/walk.py
> +                    if (self.travel_angle < 0 and self.curr_pose["theta"] > self.travel_angle) or (self.travel_angle >= 0 and self.curr_pose["theta"] < self.travel_angle):
This line is a monster, we could defo simplify it and/or split into separate lines.

2020-11-06 13:07 UTC, bhenaghan commented on minitask2/Lewis/walk.py
> +                    progress = sqrt((self.last_pose["x"] - self.curr_pose["x"])** 2 + (self.last_pose["y"] - self.curr_pose["y"])** 2)
**nitpick:** you should have a space before the `**`

2020-11-06 13:07 UTC, bhenaghan commented on minitask2/Lewis/obstacle_avoidance.py
> +        if str(data.data) == str(3):
I don't know why you're casting to string here? the `str(3)` is defo redundant as you could just do `"3"`.

2020-11-06 13:07 UTC, bhenaghan commented on minitask2/Lewis/wall_follow_right.py
> +            if scan.ranges[i] < min_val_right:
you can replace these two lines with `min_val_right = min(min_val_right, scan.ranges[i]` - Its not absolutely better but most people prefer it. It also has the advantage of branchless programming, which leads to an almost imperceptible increase in performance! branchless programming is generally a good habit to get into though, especially in python examples like this, as min() can be implemented as a fast bit of `c` code in some interpreters as its part of the standard library.

2020-11-06 13:07 UTC, bhenaghan commented on minitask2/Lewis/wall_follow_right.py
> +                    self.blocking_publisher.publish(1)
lines `86, 87, 96, 97` really mean nothing when its just magic numbers (not constants).

2020-11-06 13:13 UTC, merged